INFO:gstomd.corpus:Settings : dest_folder documents_archive, pydrive_settings 
DEBUG:gstomd:gsuiteTomd  Created
DEBUG:gstomd.corpus:
----F :                                                   |                    |                    |
DEBUG:gstomd.corpus:.
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/dev/GsuiteToMd/gstomd/__main__.py", line 73, in <module>
    main()
  File "/home/ec2-user/dev/GsuiteToMd/gstomd/__main__.py", line 67, in main
    folder_id=folder_id, root_folder_name=folder_name,
  File "/home/ec2-user/dev/GsuiteToMd/gstomd/corpus.py", line 323, in Folder
    f.fetch()
  File "/home/ec2-user/dev/GsuiteToMd/gstomd/corpus.py", line 203, in fetch
    logger.debug("%d folders found", sum(1 for x in file_list))
  File "/home/ec2-user/dev/GsuiteToMd/gstomd/corpus.py", line 203, in <genexpr>
    logger.debug("%d folders found", sum(1 for x in file_list))
  File "/home/ec2-user/dev/GsuiteToMd/gstomd/corpus.py", line 355, in get_list
    return pydrive_retry(next, file_list, None)  # noqa: E731
  File "/home/ec2-user/dev/python_env/lib/python3.7/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/ec2-user/dev/python_env/lib/python3.7/site-packages/funcy/flow.py", line 125, in retry
    return call()
  File "/home/ec2-user/dev/python_env/lib/python3.7/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/ec2-user/dev/GsuiteToMd/gstomd/corpus.py", line 340, in pydrive_retry
    result = call(*args, **kwargs)
  File "/home/ec2-user/dev/python_env/lib/python3.7/site-packages/pydrive2/apiattr.py", line 150, in __next__
    result = self._GetList()
  File "/home/ec2-user/dev/python_env/lib/python3.7/site-packages/pydrive2/auth.py", line 60, in _decorated
    self.auth.LocalWebserverAuth()
  File "/home/ec2-user/dev/python_env/lib/python3.7/site-packages/pydrive2/auth.py", line 125, in _decorated
    code = decoratee(self, *args, **kwargs)
  File "/home/ec2-user/dev/python_env/lib/python3.7/site-packages/pydrive2/auth.py", line 262, in LocalWebserverAuth
    httpd.handle_request()
  File "/usr/lib64/python3.7/socketserver.py", line 294, in handle_request
    ready = selector.select(timeout)
  File "/usr/lib64/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=1063854287655-v6f5eq8r8k3kcpre0m1b49c5vpu7ccac.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8090%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code

